Entel/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.ventas import views


#from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.productos.urls', 'productos'), namespace='producto')),
    path('', views.home_view, name='home'),
    path('', include(('apps.ventas.urls', 'ventas'), namespace='ventas'))
    
    
    
]

apps/productos/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import ProductoCreate, ProductoList, ProductoUpdate

urlpatterns = [
    path('crear_producto/', ProductoCreate.as_view() , name='crear_producto'),
    path('listar_producto/', ProductoList.as_view() , name='listar_producto'),
    path('editar_producto/<int:pk>', ProductoUpdate.as_view() , name='editar_producto'),
]

apps/ventas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import VentasList,VentasCreate,VentasUpdate

urlpatterns = [
    path('crear_ventas/', VentasCreate.as_view() , name='crear_ventas'),
    path('listar_ventas/', VentasList.as_view() , name='listar_ventas'),
    path('editar_ventas/<int:pk>', VentasUpdate.as_view() , name='editar_ventas'),
]

apps/productos/models.py
from django.db import models

# Create your models here.
class Productos(models.Model):
    nombre = models.TextField()
    unidades = models.IntegerField()

apps/vendedores/models.py
from django.db import models

# Create your models here.


class Vendedores(models.Model):
    nombreCompleto  = models.TextField()
    fechaNacimiento = models.DateTimeField()

apps/ventas/models.py
from django.db import models

# Create your models here.


class Ventas(models.Model):
    fecha       = models.DateField()
    comentarios = models.TextField()

apps/productos/forms.py
from django import forms
from apps.productos.models import Productos

class ProductoForm(forms.ModelForm): 
    class Meta                     : 
        model                      = Productos
        fields                     = [
            'nombre',
            'unidades',
        ]
        label                      = {
            'nombre'               : 'Nombre',
            'unidades'             : 'Unidades',
            
        }
        widget                     = {
            'nombre'               : forms.Textarea(attrs = {'class': 'form-control'}),
            'unidades'             : forms.TextInput(attrs={'class':'form-control'}),
            
            
        }

apps/ventas/forms.py
from django import forms
from apps.ventas.models import Ventas

class VentasForm(forms.ModelForm): 
    class Meta                   : 
        model                    = Ventas
        fields                   = [
            'fecha',
            'comentarios'
        ]
        label                    = {
            'fecha'              : 'Fecha',
            'comentarios'        : 'Comentarios',
            
        }
        widget                   = {
            'fecha'              : forms.DateInput(attrs  = {'class': 'form-control'}),
            'comentarios'        : forms.Textarea(attrs = {'class': 'form-control'}),
            
            
        }

apps/productos/views.py
from django.shortcuts import render
from apps.productos.models import Productos
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DetailView, DeleteView
from django.urls import reverse, reverse_lazy
from apps.productos.forms import ProductoForm



# Create your views here.

class ProductoCreate(CreateView): 
    model                       = Productos
    template_name               = 'productos/productos_form.html'
    fields                      = "__all__" 
    success_url                 = reverse_lazy('producto:listar_producto')

    def get_succes_url(self):
        return reverse('productos:listar_producto.html')

class ProductoList(ListView)    : 
    model                       = Productos
    template_name               = 'productos/listar_producto.html'
    context_object_name         = 'productos'
    queryset                    = Productos.objects.all()

class ProductoUpdate(UpdateView): 
    model                       = Productos
    form_class                  = ProductoForm
    template_name               = 'productos/productos_form.html'
    success_url                 = reverse_lazy('producto:listar_producto')

apps/vendedores/views.py
from django.shortcuts import render

# Create your views here.

apps/ventas/views.py
from django.shortcuts import render
from apps.ventas.models import Ventas
from apps.ventas.forms import VentasForm
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DetailView, DeleteView
from django.urls import reverse, reverse_lazy

# Create your views here.

def home_view(request,*args, **kwargs): 
    return render(request,"home.html",{})


class VentasList(ListView)      : 
      model                     = Ventas
      template_name             = 'ventas/listar_ventas.html'
      context_object_name       = 'ventas'
      queryset                  = Ventas.objects.all()

      def get_succes_url(self):
          return reverse('ventas:listar_ventas.html')


class VentasCreate(CreateView)  : 
      model                     = Ventas
      template_name             = 'ventas/crear_ventas.html'
      fields                    = "__all__" 
      success_url               = reverse_lazy('ventas: crear_ventas')

      #def get_succes_url(self)  : 
       #   return reverse('ventas: listar_ventas')


class VentasUpdate(UpdateView)  : 
    model                       = Ventas
    form_class                  = VentasForm
    template_name               = 'ventas/crear_ventas.html'
    success_url                 = reverse_lazy('ventas:listar_ventas')
    #queryset                    = Ventas.objects.all()

    
           
        
    

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Entel{% endblock %}</title>
     
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
</head>
<body>
  
    <header>{%block navbar%}
      
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">ENTEL</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item .active">
                  <a class="nav-link" href="{%url 'producto:crear_producto' %}">Crear Producto<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item .active">
                  <a class="nav-link" href="{%url 'producto:listar_producto' %}">Listar Producto</a>
                </li>
                <li class="nav-item .active">
                    <a class="nav-link" href="{%url 'ventas:crear_ventas'%}">Venta</a>
                </li>
                <li class="nav-item .active">
                  <a class="nav-link" href="{%url 'ventas:listar_ventas' %}">Listar Ventas</a>
              </li>                       
              </ul>
            </div>
          </nav>

          
          {%endblock%}
      </header>

      
      {%block contenido%}{%endblock%}
      

 


    
</body>
</html>

templates/productos/listar_producto.html
{%extends 'home.html'%}
{% load staticfiles %}


{%block contenido%}
<table class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="col-general">
    
                <td scope="col"><strong>ID</strong></td>
                <td scope="col"><strong>NOMBRE</strong></td>
                <td scope="col"><strong>UNIDADES</strong></td>
            </tr>
    
        </thead>
        <tbody>
            {% if productos %}
            {% for producto in productos %}
            <tr id="row-listar-producto">
    
                <td>{{ producto.id }}</td>
                <td>{{ producto.nombre }}</td>
                <td>{{ producto.unidades }}</td>
                <td>
                    <form method="POST" action="#">
                        {% csrf_token %}
                        <div class="btn-group">
                            <a href="#" title="Ver" type="button"
                                class="btn btn-outline-primary">Ver </a>
                            <a href="{%url 'producto:editar_producto' producto.id%}" title="Editar" type="button"
                                class="btn btn-secundary">Editar </a>
                            <button class="btn btn-danger" onclick="return eliminar();" type="submit">Eliminar</button>
                        </div>
                    </form>
                </td>
                <td>
                    
                </td>
            </tr>
            
            {% endfor %}
            {% else %}
            <h2>No existen productos registrados</h2>
            {% endif %}
        </tbody>
    </table>
{%endblock%}

templates/productos/productos_form.html
{%extends 'home.html'%}
{% load staticfiles %}

{%block contenido%}
<form method="POST">
    {% csrf_token %}
    {% if error %}
        <h2>{{ error }}</h2>
    {% else %}
    <div class="card">
        <div class="card-header">
            <h2><strong>FORMULARIO INGRESO PRODUCTO</strong></h2>
        </div>
        <div class="card-body card-block">
            <form action="{% url 'producto:crear_producto' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">

                <div class="row form-group">
                    <div class="col col-md-3">{{ form.nombre.label }}</div>
                    <div class="col-12 col-md-9">{{ form.nombre }}</div>
                </div>
                <div class="row form-group">
                    <div class="col col-md-3">{{ form.unidades.label }}</div>
                    <div class="col-12 col-md-9">{{ form.unidades }}</div>
                </div>
                
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-primary">GUARDAR PRODUCTO</button>
                    
                    <button type="reset"  class="btn btn-outline-secundary">CANCELAR</button>
                </div>
            </form>
        </div>

    </div>
    {%endif%}
    
</form>
{%endblock%}   

templates/ventas/crear_ventas.html
{%extends 'home.html'%}
{% load staticfiles %}

{%block contenido%}
<form method="POST">
    {% csrf_token %}
    {% if error %}
        <h2>{{ error }}</h2>
    {% else %}
    <div class="card">
        <div class="card-header">
            <h2><strong>GENERAR VENTA</strong></h2>
        </div>
        <div class="card-body card-block">
            <form action="{% url 'ventas:crear_ventas' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">

                <div class="row form-group">
                    <div class="col col-md-3">{{ form.fecha.label }}</div>
                    <div class="col-12 col-md-9">{{ form.fecha }}</div>
                </div>
                <div class="row form-group">
                    <div class="col col-md-3">{{ form.comentarios.label }}</div>
                    <div class="col-12 col-md-9">{{ form.comentarios }}</div>
                </div>
                
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-primary">GENERAR</button>
                    
                    <button type="reset"  class="btn btn-outline-secundary">CANCELAR</button>
                </div>
            </form>
        </div>

    </div>
    {%endif%}
    
</form>
{%endblock%}

templates/ventas/listar_ventas.html
{%extends 'home.html'%}
{% load staticfiles %}


{%block contenido%}
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr class="col-general">

            <td scope="col"><strong>ID</strong></td>
            <td scope="col"><strong>FECHA</strong></td>
            <td scope="col"><strong>COMENTARIOS</strong></td>
        </tr>

    </thead>
    <tbody>
        {% if ventas %}
        {% for ventas in ventas %}
        <tr id="row-listar-ventas">

            <td>{{ ventas.id }}</td>
            <td>{{ ventas.fecha }}</td>
            <td>{{ ventas.comentarios }}</td>
            
            <td>
                <form method="POST" action="#">
                    {% csrf_token %}
                    <div class="btn-group">
                        <a href="#" title="Ver" type="button"
                            class="btn btn-outline-primary">Ver </a>
                        <a href="{%url 'ventas:editar_ventas' ventas.id%}" title="Editar" type="button"
                            class="btn btn-secundary">Editar </a>
                        <button class="btn btn-danger" onclick="return eliminar();" type="submit">Eliminar</button>
                    </div>
                </form>
            </td>
            <td>
                
            </td>
        </tr>
        
        {% endfor %}
        {% else %}
        <h2>No existen productos registrados</h2>
        {% endif %}
    </tbody>
</table>
{%endblock%}